### ISSUE TITLE
Server Crash/Overflow loop

### ISSUE THREAD

**Issue by rob5251** [DoubleDoorDevelopment/TorchTools#10]
This just started happening recently on my server. The console gets spammed with the following and then it eventually crashes. I've provided the full crash log as well (pastebin)

```
 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) ~[ForgeEventFactory.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler_5_TorchTools_playerInteractEventHandler_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
08.01 17:18:20 [Server] INFO at net.doubledoordev.torchtools.TorchTools.playerInteractEventHandler(TorchTools.java:117) ~[TorchTools.class:?]
08.01 17:18:20 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:428) ~[mx.class:?]
08.01 17:18:20 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) ~[ForgeEventFactory.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler_5_TorchTools_playerInteractEventHandler_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
08.01 17:18:20 [Server] INFO at net.doubledoordev.torchtools.TorchTools.playerInteractEventHandler(TorchTools.java:117) ~[TorchTools.class:?]
08.01 17:18:20 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:428) ~[mx.class:?]
08.01 17:18:20 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) ~[ForgeEventFactory.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler_5_TorchTools_playerInteractEventHandler_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
08.01 17:18:20 [Server] INFO at net.doubledoordev.torchtools.TorchTools.playerInteractEventHandler(TorchTools.java:117) ~[TorchTools.class:?]
08.01 17:18:20 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:428) ~[mx.class:?]
08.01 17:18:20 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) ~[ForgeEventFactory.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.ASMEventHandler_5_TorchTools_playerInteractEventHandler_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
08.01 17:18:20 [Server] INFO at net.doubledoordev.torchtools.TorchTools.playerInteractEventHandler(TorchTools.java:117) ~[TorchTools.class:?]
08.01 17:18:20 [Server] INFO at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:428) ~[mx.class:?]
08.01 17:18:20 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) ~[ForgeEventFactory.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:146) ~[EventBus.class:1.7.10-1614.UNOFFICIAL]
08.01 17:18:20 [Server] INFO at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:500) ~[?:1.8.0_65]
08.01 17:18:20 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_65]
08.01 17:18:20 [Server] INFO java.lang.StackOverflowError
08.01 17:18:20 [Server] ERROR Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent@3765a1b:
08.01 17:18:20 [Multicraft] Skipped 10382 lines due to rate limit (30/s)
```

Pastebin / full crash log:
http://pastebin.com/QrbzurP3

**Comment by dries007** [comment]
Is Modded: Definitely; Server brand changed to '**kcauldron,cauldron,craftbukkit,mcpc**,fml,forge'

Guess what, just like any other mod, we don't support any bukkit BS. Please remove and make sure it happens without it.
